---
title: "incompatibility_study"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(admixr)
library(tidyverse)
library(dplyr)
library(data.table)
library(cowplot)
library(ggbeeswarm)
library(reshape2)


nice_layout<-   theme_cowplot(font_size = 22)+
  #   panel_border(color = "grey85", size = 1, linetype = 1,
  # remove = FALSE, "black") +
    theme(strip.background = element_rect(fill = "#ffffff"), text = element_text(size = 22))


my_cols <- c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a')


stackbarcolors<- c("ambiguous"="#808080", "caudatus"="#a6cee3", "cruentus"="#1f78b4", "hypochondriacus"="#b2df8a", "hybridus_CA"="#33a02c", "hybridus_SA"="#f8bf68", "quitensis"="#fb9a99")
```

```{r}

dados_30d<- fread("/Users/josedias/Downloads/incompatibility_study - documentation_post_transp_updat.tsv" )

dados_30d %>%
  group_by(cross_type) %>%
  dplyr::summarise(count(died)) %>%
  # melt(id.vars="cross_type") 
mutate(died=x) %>%
ggplot(., aes(x=as.factor(cross_type), y=freq, fill=died)) +
geom_bar(stat="identity") +
  
  nice_layout


dados_30d %>%
  group_by(cross_type) %>%
  dplyr::summarise(count(died)) %>%
mutate(died=x) %>%
ggplot(., aes(x=as.factor(cross_type), y=freq, fill=died)) +
geom_bar(stat="identity") +
  nice_layout


dados_30d %>%
    # group_by(cross_type) %>%
ggplot(., aes(x=as.factor(cross_type), y=as.numeric(`30d_growth`)), fill=cross_type) +
geom_beeswarm(aes(color=type)) +
nice_layout

dados_30d %>%
    melt(id.vars="cross_type") %>%
  filter(grep("gowth"), variable)

cor(cross_type,`30d_growth`)
```

