---
title: "R Notebook"
output: html_notebook
---





#packages loading
``` {r}
library(reticulate)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(cowplot)
library(data.table)

# install.packages('ggbeeswarm')
library(ggbeeswarm)
my_cols <- c('#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6','#6a3d9a')

pop.cols<- c("caudatus"="#a6cee3", "cruentus"="#1f78b4", "hypochondriacus"="#b2df8a", "hybridus_CA"="#33a02c","hybridus_SA"="#fdbf6f", "quitensis"="#fb9a99")


nice_layout<-   
    panel_border(color = "grey85", size = 1, linetype = 1,
  remove = TRUE, "black") +
  theme(strip.background = element_rect(fill = "#ffffff"), text = element_text(size = 30))

```



## by population

```{r}
# population_abba<- fread("/Users/josedias/OneDrive/Stetter_Lab/correct_trees_pop.txt")


population_abba<- fread('/Users/josedias/Documents/PhD/projects/GeneFlow/data/processed/abba/109int_tubercualtus_ERR3220406.out.Observed.txt')




  
    correct_trees_caudatus_bypop<- population_abba %>% #allow quitensis-->caudatus gene flow
    filter((H1=="caudatus" & ((H2=="quitensis" | H2=="hybridus_SA") & H3!="hybridus_SA" & D<0)) | H2=="caudatus" & ((H1=="quitensis" | H1=="hybridus_SA") & H3!="hybridus_SA" & D >0)) 

      
  correct_trees_quitensis_bypop<- population_abba %>%
    filter((H1=="quitensis" & ((H2=="hybridus_SA" | H2=="caudatus")  & D<0)) | H2=="quitensis" & ((H1=="hybridus_SA" | H1=="caudatus") & D >0))           

  
      
  correct_trees_hybridus_SA_extended_bypop<- population_abba %>%
    filter((H1=="hybridus_SA" & ((H2=="quitensis" | H2=="caudatus")  & D<0)) | H2=="hybridus_SA" & ((H1=="quitensis" | H1=="caudatus") & D >0)) 
  

    
    
   correct_trees_cruentus_bypop<-  population_abba %>%
    filter((H1=="cruentus" & ((H2=="hypochondriacus" | H2=="hybridus_CA") & H3!="hybridus_CA" & H3!="hypochondriacus" & D<0 )) | H2=="cruentus" & ((H1=="hypochondriacus" | H1=="hybridus_CA") & H3!="hybridus_CA" & H3!="hypochondriacus"  & D >0))  

  
    correct_trees_hypochondriacus_bypop<-population_abba %>%
    filter((H1=="hypochondriacus" & ((H2=="cruentus" | H2=="hybridus_CA") & H3!="hybridus_CA" & H3!="cruentus" & D < 0)) | H2=="hypochondriacus" & ((H1=="cruentus" | H1=="hybridus_CA") & H3!="hybridus_CA" & H3!="cruentus" & D > 0 )) 
      
        
    correct_trees_hybridus_CA_bypop<- population_abba %>%
    filter((H1=="hybridus_CA" & ((H2=="cruentus" | H2=="hypochondriacus") & H3!="hybridus_CA" & H3!="cruentus" & D < 0)) | H2=="hybridus_CA" & ((H1=="cruentus" | H1=="hybridus_CA") & H3!="hybridus_CA" & H3!="cruentus" & D > 0 ))

  

correct_trees_extended_bypop<- rbind(correct_trees_caudatus_bypop, correct_trees_cruentus_bypop, correct_trees_hypochondriacus_bypop, correct_trees_hybridus_CA_bypop, correct_trees_hybridus_SA_extended_bypop, correct_trees_quitensis_bypop)
  





```

#data loading

```{r}


population_abba<-fread("../data/processed/abba_pop_R_sc16.Observed.txt")
```


# Data preperation



```{r}
# amaranth_list<- fread('/Users/josedias/Downloads/amaranth_list_geneflow.tsv', header=T)


inidviduals_meta_H1<- amaranth_list %>%
  select(sample_name, Population,origin, color ) %>%
  rename(H1=Population) %>%
  rename(H1origin=origin)
  

inidviduals_meta_H2<- amaranth_list %>%
  select(sample_name, Population,origin, color ) %>%
    rename(H2=Population)%>%
  rename(H2origin=origin)


inidviduals_meta_H3<- amaranth_list %>%
  select(sample_name, Population,origin, color ) %>%
    rename(H3=Population)%>%
  rename(H3origin=origin)



correct_trees_caudatus<- population_abba %>%
    filter((H1=="caudatus" & ((H2=="quitensis" | H2=="hybridus_SA") & H3!="hybridus_SA" & H3!="quitensis" & D<0)) | H2=="caudatus" & ((H1=="quitensis" | H1=="hybridus_SA") & H3!="hybridus_SA" & H3!="quitensis" & D >0)) 
  
  
    correct_trees_caudatus_extended<- population_abba %>% #allow quitensis-->caudatus gene flow
    filter((H1=="caudatus" & ((H2=="quitensis" | H2=="hybridus_SA") & H3!="hybridus_SA" & D<0)) | H2=="caudatus" & ((H1=="quitensis" | H1=="hybridus_SA") & H3!="hybridus_SA" & D >0)) 
  
  
      correct_trees_quitensis<- population_abba %>%
    filter((H1=="quitensis" & ((H2=="hybridus_SA" | H2=="caudatus") & H3!="caudatus" & H3!="quitensis" & D<0)) | H2=="quitensis" & ((H1=="hybridus_SA" | H1=="caudatus") & H3!="quitensis" & H3!="hybridus_SA" & D >0)) 
  
      
      
  correct_trees_quitensis_extended<- population_abba %>%
    filter((H1=="quitensis" & ((H2=="hybridus_SA" | H2=="caudatus")  & D<0)) | H2=="quitensis" & ((H1=="hybridus_SA" | H1=="caudatus") & D >0))           
      
    
  correct_trees_hybridus_SA<- population_abba %>%
    filter((H1=="hybridus_SA" & ((H2=="quitensis" | H2=="caudatus") & H3!="caudatus" & H3!="quitensis" & D<0)) | H2=="hybridus_SA" & ((H1=="quitensis" | H1=="caudatus") & H3!="hybridus_SA" & H3!="quitensis" & D >0)) 
  

      
  correct_trees_hybridus_SA_extended<- population_abba %>%
    filter((H1=="hybridus_SA" & ((H2=="quitensis" | H2=="caudatus")  & D<0)) | H2=="hybridus_SA" & ((H1=="quitensis" | H1=="caudatus") & D >0)) 
  

    
    
   correct_trees_cruentus<-  population_abba %>%
    filter((H1=="cruentus" & ((H2=="hypochondriacus" | H2=="hybridus_CA") & H3!="hybridus_CA" & H3!="hypochondriacus" & D<0 )) | H2=="cruentus" & ((H1=="hypochondriacus" | H1=="hybridus_CA") & H3!="hybridus_CA" & H3!="hypochondriacus"  & D >0))  

  
    correct_trees_hypochondriacus<-population_abba %>%
    filter((H1=="hypochondriacus" & ((H2=="cruentus" | H2=="hybridus_CA") & H3!="hybridus_CA" & H3!="cruentus" & D < 0)) | H2=="hypochondriacus" & ((H1=="cruentus" | H1=="hybridus_CA") & H3!="hybridus_CA" & H3!="cruentus" & D > 0 )) 
      
        
    correct_trees_hybridus_CA<- population_abba %>%
    filter((H1=="hybridus_CA" & ((H2=="cruentus" | H2=="hypochondriacus") & H3!="hybridus_CA" & H3!="cruentus" & D < 0)) | H2=="hybridus_CA" & ((H1=="cruentus" | H1=="hybridus_CA") & H3!="hybridus_CA" & H3!="cruentus" & D > 0 ))

  

correct_trees<- rbind(correct_trees_caudatus, correct_trees_cruentus, correct_trees_hypochondriacus, correct_trees_hybridus_CA, correct_trees_hybridus_SA, correct_trees_quitensis)
  

correct_trees_extended<- rbind(correct_trees_caudatus_extended, correct_trees_cruentus, correct_trees_hypochondriacus, correct_trees_hybridus_CA, correct_trees_hybridus_SA_extended, correct_trees_quitensis_extended)
  

```




# plot by popualtion

```{r}

correct_trees_extended_bypop_test<- correct_trees_extended

correct_trees_extended_bypop_test %>%
  unite("trees", H1:H3, remove = FALSE) %>%
      # filter( Z >=3 | Z<=-3) %>% #remove non-significant rows
# filter((D<0 & ((H1=="hypochondriacus" | H1 =="cruentus" | H1=="caudatus")  & (H3=="hypochondriacus" | H3 =="cruentus" | H3=="caudatus"))) | (D>0 & ((H2=="hypochondriacus" | H2 =="cruentus" | H2=="caudatus")  & (H3=="hypochondriacus" | H3 =="cruentus" | H3=="caudatus")))) %>%
     ggplot( aes( x=D, y=trees)) +
  # geom_bar(stat="identity")  +
   # geom_bar(stat = "identity") +
geom_point(lwd = 5, position = position_dodge(preserve = "single") ) +
      theme_cowplot() +
   ggtitle("by popuation, only crops, with Z-score filter ") +
      theme(
        # axis.title.y=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        # axis.title.x = element_text(size = 20),
        # axis.text.x = element_text(size = 20),
) +
# facet_grid(H2~., space="free", scale="free") +
geom_vline(xintercept=0, linetype="dotted") +
  scale_fill_manual(values=pop.cols) +
    scale_color_manual(values=pop.cols) +
  nice_layout


```



