#!/bin/bash -l
#SBATCH --partition=devel
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=46gb
#SBATCH --account=UniKoeln
#SBATCH --mail-user=jgoncal1@uni-koeln.de
#SBATCH --error /scratch/jgoncal1/logs/errors/bacftools_annotate_%j
#SBATCH -o /scratch/jgoncal1/logs/bacftools_annotate_%j
#SBATCH -D /projects/ag-stetter/jdias/projects/GeneFlow/code/


ichr=0 #number of haplotypes identified per chrossome

vcf_file_prefix="../data/processed/vcf_files/VCF_subset_introgression108_Scaffold_" # preifx of files generated by csplit

for scaffold in {1..16};do # loop per scaffold

echo $vcf_file_prefix$scaffold.recode.vcf.gz 
echo ../data/processed/vcf_files/annotated_$(basename $vcf_file_prefix)$scaffold.recode.vcf.gz 

bcftools annotate --set-id +'%CHROM\_%POS' $vcf_file_prefix$scaffold.recode.vcf.gz > ../data/processed/vcf_files/annotated_$(basename $vcf_file_prefix)$scaffold.recode.vcf.gz 

done
