---
title: "R Notebook"
output: html_notebook
---



# packages loading

```{r, eval= FALSE, echo=FALSE}
library(cowplot)
library(ggplot2)
library(data.table)
library(tidyverse)
library(dplyr)

my_cols<- c("caudatus"="#a6cee3", "cruentus"="#1f78b4", "hypochondriacus"="#b2df8a", "hybridus_CA"="#33a02c","hybridus_SA"="#fdbf6f", "quitensis"="#fb9a99")
nice_layout<-   
  theme_cowplot(22) +
    panel_border(color = "#ffffff", size = 1, linetype = 1,
  remove = TRUE, "black") +
  theme(strip.background = element_rect(fill = "#ffffff"), text = element_text(size = 22))

options(scipen = 999)

addUnits <- function(n) {
  labels <- ifelse(n < 1000, n,  # less than thousands
                   ifelse(n < 1e6, paste0(round(n/1e3)),  # in thousands
                          ifelse(n < 1e9, paste0(round(n/1e6)),  # in millions
                                 ifelse(n < 1e12, paste0(round(n/1e9)), # in billions
                                        ifelse(n < 1e15, paste0(round(n/1e12)), # in trillions
                                               'too big!'
                                        )))))
  return(labels)
}

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

devtools::install_github("PhanstielLab/bedtoolsr", force = T)
options(bedtools.path = "/Users/josedias/miniconda3/bin/")

clear_layout<-   theme_cowplot(font_size = 22)+
  #   panel_border(color = "grey85", size = 1, linetype = 1,
  # remove = FALSE, "black") +
    theme(strip.background = element_rect(fill = "#ffffff"), text = element_text(size = 22))

```

# data loading and preparation

```{r}


sweeps_caudatus<-fread("/Users/josedias/mount/projects/ag-stetter/jdias/projects/PopAmaranth/data/output/sweep_caudatus.BedGraph") %>%
  dplyr::rename(chr=V1, windowStart = V2, windowEnd=V3, sweep_height=V4) %>%
  filter(grepl("Scaffold", chr)) %>%
      mutate(CHR=gsub("Scaffold_","", chr)) %>%
     mutate_at(c('CHR'), as.numeric) %>%
            mutate(window_center=round((as.numeric(windowStart)+as.numeric(windowEnd)/2))) 



# ## create BPcum for drawing mahantan plot alongn the genome 
# sweeps_caudatus.df<- sweeps_caudatus %>%
#    group_by(CHR) %>%
#     summarise(chr_len=max(windowEnd)) %>%
#      mutate(tot=cumsum(chr_len)-chr_len) %>%
#     select(-chr_len) %>%
#     left_join(sweeps_caudatus, ., by=c("CHR")) %>%
#   arrange(chr, windowEnd) %>%
#     mutate( BPcum=windowEnd+tot) %>%
#   mutate(window_center=round(((windowStart+windowEnd)/2))) %>%
#       select(CHR, windowStart, windowEnd, sweep_height, window_center) %>%
#               mutate(Position = window_center/1e6) %>%
#   mutate(sweep_height=as.numeric("-1.2"))

sweeps_caudatus.df$sweep_height<-as.numeric()

 sweeps_caudatus.df<- topwindows

sweeps_caudatus.df$height<-as.numeric(-1.1)


crops_tree<- fread("/Users/josedias/mount/scratch/jgoncal1/data/processed/dsuite_nonoverlpaping/cruentus_hypochondriacus_caudatus_localFstats_Dsuite_Dinvestigate_w100_step_100_fullgenome_crops_trios_100_100.txt") 

  
crops_tree<- crops_tree %>%
    filter(str_detect(chr, "Scaffold")) %>%
        mutate(window_center=round(((windowStart+windowEnd)/2))) %>%
              mutate(Position = window_center/1e6) %>%
    mutate(difference=windowEnd-windowStart) %>%
    mutate(CHR=gsub("Scaffold_","", chr)) %>%
   mutate_at(c('CHR'), as.numeric) 

df.tmp <-
crops_tree %>%
   group_by(chr) %>% 
    summarise(chr_len=max(windowEnd)) %>%
     mutate(tot=cumsum(chr_len)-chr_len) %>%
    select(-chr_len) %>%
    left_join(crops_tree, ., by=c("chr")) %>%
  arrange(chr, windowEnd) %>%
    mutate( BPcum=windowEnd+tot) %>%
  mutate( is_highlight=ifelse(f_dM>quantile(crops_tree$f_dM, .99), "yes", "no")) %>%
    mutate( is_annotate=ifelse(f_dM>quantile(crops_tree$f_dM, .99), "yes", "no"))

  axisdf <- df.tmp %>% group_by(CHR) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )
  
  
  
top_windows_crops_tree <-  df.tmp %>%
    filter(str_detect(chr, "Scaffold")) %>%
                 filter(f_dM>quantile(df.tmp$f_dM, .995)) %>%
            mutate(Position = window_center/1e6) %>%
    select(CHR, windowStart, windowEnd, f_dM, Position, window_center)



bottom_windows_crops_tree <-  df.tmp %>%
    filter(str_detect(chr, "Scaffold")) %>%
                 filter(f_dM<quantile(df.tmp$f_dM, .005)) %>%
            mutate(Position = window_center/1e6) %>%
    select(CHR, windowStart, windowEnd, f_dM, Position, window_center)



 

interesection_crops_tree_sweep_tops<- bedtoolsr::bt.intersect(top_windows_crops_tree, sweeps_caudatus.df ) %>%
  rename(CHR=V1, windowStart=V2, windowEnd=V3, f_dM=V4)  %>%
          mutate(window_center=round(((windowStart+windowEnd)/2))) %>%
              mutate(Position = window_center/1e6) 
  

interesection_crops_tree_sweep_bottom<- bedtoolsr::bt.intersect(bottom_windows_crops_tree, sweeps_caudatus.df) %>%
  rename(CHR=V1, windowStart=V2, windowEnd=V3, f_dM=V4) %>%
          mutate(window_center=round(((windowStart+windowEnd)/2))) %>%
              mutate(Position = window_center/1e6) 

interesection_crops_tree_sweeps_all<-rbind(interesection_crops_tree_sweep_bottom, interesection_crops_tree_sweep_tops)
interesection_crops_tree_sweeps_all$height<-as.numeric(-1.1)

  
  
```

```{r}


quantile(crops_tree$f_dM, .005)


# plot_sweep_caudatus<-     ggplot(sweeps_caudatus.df, aes(x=BPcum, y=sweep_height)) +
#  geom_point(color="#808080",  size=0.5) +
#             nice_layout +
#       facet_grid(.~chr, scales = "free_x", space = "free_x") +
#               # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
#     # scale_y_continuous(breaks=1, expand = c(0, 0.05)) +  # expand=c(0,0)removes space between plot area and x axis  +
#   scale_x_continuous(labels = addUnits) +
#       theme(axis.text.x = element_text(angle=45, hjust = 1, vjust=1, size=10), legend.position = "none") +
#     xlab("Position (Mb")  +
#       ylim(1,1) 
# 
# 
# 
#     ggplot(df.tmp, aes(x=BPcum, y=f_dM)) +
#     # Show all points
#     geom_point(aes(color=as.factor(chr)), alpha=0.8, size=2) +
#             nice_layout +
#     scale_color_manual(values = rep(my_cols, 16 )) +
#           scale_fill_manual(values = rep(my_cols, 16 )) +
#         scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
#     scale_y_continuous(expand = c(0, 0)) +  # expand=c(0,0)removes space between plot area and x axis  +
#     xlab("Chrosmosome") +
#       theme(axis.text.x = element_text(angle=45, hjust=1)) 
#   
#     


sweeps_caudatus.df<- sweeps_caudatus.df %>%
    mutate(windowCenter=round(((windowStart+windowEnd)/2))) %>%
  rename(CHR=chr)

  # mutate(window_center=windowCenter/1e6) %>%

       plot_fd_crops <-
    ggplot(df.tmp, aes(x=window_center, y=f_dM)) +
    # Show all points
    geom_point(aes(alpha=0.05), alpha=0.05, color="#808080",  size=0.5) +
         geom_point(data=top_windows_crops_tree, 
             aes(x=window_center,y=f_dM), 
             color='#009E73',fill="#009E73",
             size=1.1) +
  geom_line(data=df.tmp, aes(x=window_center, y=quantile(crops_tree$f_dM, .995)), color="#009E73", fill="#009E73", linetype="dashed") +
    geom_point(data=bottom_windows_crops_tree, aes(x=window_center, y=f_dM),color = "#808080", alpha=0.3)  +
  geom_point(data=bottom_windows_crops_tree, 
             aes(x=window_center,y=f_dM), 
             color='#56B4E9', fill="#56B4E9",
             size=1.1) +
  geom_line(data=df.tmp, aes(x=window_center, y=quantile(crops_tree$f_dM, .005)), color="#56B4E9", fill="#56B4E9",  linetype="dashed") +
                  geom_point(data=interesection_crops_tree_sweeps_all, aes(x=window_center, y=f_dM),
             size=2.5,  color="#D55E00") +
         
      facet_grid(.~CHR, scales = "free", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
                 clear_layout +
               theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank(), panel.spacing = unit(0.2,'lines')
) +
                          geom_point(data=sweeps_caudatus.df, aes(x=windowStart, y=height), shape="|", color="#000000",  size=5) 


       
plot_fd_crops
       
        ggsave("/Users/josedias/Documents/PhD/projects/GeneFlow/text/amaranth_introgression/figures/fdM_sweeps_cau_hyp_cru_cb_full_genome.png", plot_fd_crops, bg='white', width=20, height = 5)
```

```{r}


df.tmp_chr2<-   df.tmp %>% 
  filter(CHR=="2") %>%
  filter(Position>14.8) %>%
  filter(Position<14.95) 


bottom_windows_crops_tree_chr2 <- bottom_windows_crops_tree %>% 
  filter(CHR=="2") %>%
  filter(Position>14.8) %>%
  filter(Position<14.95) 

top_windows_crops_tree_ch2 <- top_windows_crops_tree %>% 
  filter(CHR=="2") %>%
  filter(Position>14.8) %>%
  filter(Position<14.95) 

interesection_crops_tree_sweeps_all_chr_2<- interesection_crops_tree_sweeps_all %>% 
  filter(CHR=="2") %>%
  filter(Position>14.8) %>%
  filter(Position<14.95) 


 interesection_crops_tree_sweeps_all %>% 
  filter(CHR=="2") %>%
  filter(Position>14.8) %>%
  filter(Position<14.95) 

 
 sweeps_caudatus.df_chr2<- sweeps_caudatus.df %>%
  filter(CHR=="2") %>%
  filter(Position>14.8) %>%
  filter(Position<14.95) 


 
  plot_fd_crops_chr2 <-
    ggplot(df.tmp_chr2, aes(x=Position, y=f_dM)) +
    # Show all points
    geom_point(, alpha=0.5, color="#808080",  size=0.5)  +  # Show all points
         geom_point(data=top_windows_crops_tree_ch2, 
             aes(x=Position,y=f_dM), 
             color='#009E73',fill="#009E73",
             size=1.1) +
  geom_line(data=df.tmp_chr2, aes(x=Position, y=quantile(crops_tree$f_dM, .995)), color="#009E73", fill="#009E73", linetype="dashed") +
    geom_point(data=bottom_windows_crops_tree_chr2, aes(x=Position, y=f_dM),color = "#808080", alpha=0.3)  +
  geom_point(data=bottom_windows_crops_tree_chr2, 
             aes(x=Position,y=f_dM), 
             color='#56B4E9', fill="#56B4E9",
             size=1.1) +
  geom_line(data=df.tmp_chr2, aes(x=Position, y=quantile(crops_tree$f_dM, .005)), color="#56B4E9", fill="#56B4E9",  linetype="dashed") +
                  geom_point(data=interesection_crops_tree_sweeps_all_chr_2, aes(x=Position, y=f_dM),
             size=2.5,  color="#D55E00") +
         
      facet_grid(.~CHR, scales = "free", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
                 clear_layout +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank(), panel.spacing = unit(0.2,'lines')
      ) + geom_point(data=sweeps_caudatus.df_chr2, aes(x=Position, y=sweep_height), shape="|", color="#000000",  size=5) 
  
plot_fd_crops_chr2

        # ggsave("/Users/josedias/Documents/PhD/projects/GeneFlow/text/amaranth_introgression/figures/fdM_cau_hyp_cru_cb_chr_2.png", plot_fd_crops_chr2, bg='white', width=15, height = 5)

```

```{r}
 
above_tree<- crops_tree %>%
  filter(crops_tree$f_dM>0) %>%
  select(CHR, windowStart, windowEnd)

below_tree <- crops_tree %>%
  filter(crops_tree$f_dM<0) %>%
  select(CHR, windowStart, windowEnd)
  
 bedtoolsr::bt.intersect(above_tree, below_tree )

  
 bedtoolsr::bt.intersect(top_windows_test, bottom_windows_test )

  rename(CHR=V1, windowStart=V2, windowEnd=V3, f_dM=V4)  %>%
```

