---
title: "R Notebook"
output: html_notebook
---



packages loading


```{r, eval= FALSE, echo=FALSE}
library(cowplot)
library(ggplot2)
library(data.table)
library(tidyverse)
library(dplyr)
ind.abba.cols<- c("caudatus"="#a6cee3", "cruentus"="#1f78b4", "hypochondriacus"="#b2df8a", "hybridus_CA"="#33a02c","hybridus_SA"="#fdbf6f", "quitensis"="#fb9a99")


nice_layout<-   
    panel_border(color = "#ffffff", size = 1, linetype = 1,
  remove = TRUE, "black") +
  theme(strip.background = element_rect(fill = "#ffffff"), text = element_text(size = 22))

options(scipen = 999)


addUnits <- function(n) {
  labels <- ifelse(n < 1000, n,  # less than thousands
                   ifelse(n < 1e6, paste0(round(n/1e3)),  # in thousands
                          ifelse(n < 1e9, paste0(round(n/1e6)),  # in millions
                                 ifelse(n < 1e12, paste0(round(n/1e9)), # in billions
                                        ifelse(n < 1e15, paste0(round(n/1e12)), # in trillions
                                               'too big!'
                                        )))))
  return(labels)
}


cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```


```{r}

sweeps_caudatus<-fread("/Users/josedias/mount/projects/ag-stetter/jdias/projects/PopAmaranth/data/output/sweep_caudatus.BedGraph") %>%
  rename(chr=V1, startpos = V2, endpos=V3, sweep_height=V4) %>% 
  filter(grepl("Scaffold", chr)) %>%
      mutate(CHR=gsub("Scaffold_","", chr)) %>%
     mutate_at(c('CHR'), as.numeric)

sweeps_cruentus<-fread("/Users/josedias/mount/projects/ag-stetter/jdias/projects/PopAmaranth/data/output/sweep_cruentus.BedGraph") %>%
  rename(chr=V1, startpos = V2, endpos=V3, sweep_height=V4) %>% 
  filter(grepl("Scaffold", chr)) %>%
      mutate(CHR=gsub("Scaffold_","", chr)) %>%
     mutate_at(c('CHR'), as.numeric)


sweeps_hypochondriacus<-fread("/Users/josedias/mount/projects/ag-stetter/jdias/projects/PopAmaranth/data/output/sweep_hypochondriacus.BedGraph") %>%
  rename(chr=V1, startpos = V2, endpos=V3, sweep_height=V4) %>% 
  filter(grepl("Scaffold", chr)) %>%
      mutate(CHR=gsub("Scaffold_","", chr)) %>%
     mutate_at(c('CHR'), as.numeric)


sweeps_caudatus.df<- sweeps_caudatus %>%
   group_by(CHR) %>% 
    summarise(chr_len=max(endpos)) %>%
     mutate(tot=cumsum(chr_len)-chr_len) %>%
    select(-chr_len) %>%
    left_join(sweeps_caudatus, ., by=c("CHR")) %>%
  arrange(chr, endpos) %>%
    mutate( BPcum=endpos+tot) 

  axisdf <- df.tmp %>% group_by(CHR) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )
  
  
sweeps_cruentus.df<- sweeps_cruentus %>%
   group_by(CHR) %>% 
    summarise(chr_len=max(endpos)) %>%
     mutate(tot=cumsum(chr_len)-chr_len) %>%
    select(-chr_len) %>%
    left_join(sweeps_cruentus, ., by=c("CHR")) %>%
  arrange(chr, endpos) %>%
    mutate( BPcum=endpos+tot) 

  
sweeps_hypochondriacus.df<- sweeps_hypochondriacus %>%
   group_by(CHR) %>% 
    summarise(chr_len=max(endpos)) %>%
     mutate(tot=cumsum(chr_len)-chr_len) %>%
    select(-chr_len) %>%
    left_join(sweeps_hypochondriacus, ., by=c("CHR")) %>%
  arrange(chr, endpos) %>%
    mutate( BPcum=endpos+tot) 


  axisdf <- df.tmp %>% group_by(CHR) %>% summarize(center=( max(BPcum) + min(BPcum) ) / 2 )
  
  
  
plot_sweep_caudatus<-     ggplot(sweeps_caudatus.df, aes(x=BPcum, y=sweep_height)) +
 geom_point(color="#808080",  size=0.5) +
            nice_layout +
      facet_grid(.~CHR, scales = "free_x", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(breaks=1, expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=45, hjust = 1, vjust=1, size=10), legend.position = "none") +
    xlab("Position (Mb")  +
      ylim(1,1) 
  

# crops_tree<- fread("../data/processed/dsuite_out/cruentus_hypochondriacus_caudatus_localFstats_Dsuite_Dinvestigate_w50_sc16_50_1.txt") %>%
  crops_tree<- fread("/Users/josedias/mount/scratch/jgoncal1//data/processed/dsuite_nonoverlpaping/cruentus_hypochondriacus_caudatus_localFstats_Dsuite_Dinvestigate_w100_step_100_fullgenome_crops_trios_100_100.txt") 
  

crops_tree<- crops_tree %>%
    filter(str_detect(chr, "Scaffold")) %>%
        mutate(window_center=round(((windowStart+windowEnd)/2))) %>%
              mutate(Position = window_center/1e6) %>%
    mutate(difference=windowEnd-windowStart) %>%
    mutate(CHR=gsub("Scaffold_","", chr)) %>%
   mutate_at(c('CHR'), as.numeric)




df.tmp <-
crops_tree 
  
  
  
top_windows_crops_tree <-  df.tmp %>%
    filter(str_detect(chr, "Scaffold")) %>%
                 filter(f_dM>quantile(df.tmp$f_dM, .995)) %>%
            mutate(Position = window_center/1e6)


bottom_windows_crops_tree <-  df.tmp %>%
    filter(str_detect(chr, "Scaffold")) %>%
                 filter(f_dM<quantile(df.tmp$f_dM, .005)) %>%
            mutate(Position = window_center/1e6)
  
  
    ggplot(df.tmp, aes(x=BPcum, y=f_dM)) +
    # Show all points
    geom_point(aes(color=as.factor(chr)), alpha=0.8, size=2) +
            nice_layout +
    scale_color_manual(values = rep(my_cols, 16 )) +
        scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(expand = c(0, 0)) +  # expand=c(0,0)removes space between plot area and x axis  +
    xlab("Chrosmosome") +
      theme(axis.text.x = element_text(angle=45, hjust=1)) 
    
    
    
  ################  
 
  
for_corr_evaluation<- crops_tree %>%
  select(chr,window_center,D, f_d, f_dM) 
for_corr_evaluation$f_d[!is.finite(for_corr_evaluation$f_d)] <- NA
  
correlacao<-  for_corr_evaluation %>%
  select(-chr) %>%
  cor(.,use ="complete.obs")

  get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }

uptr_correlacato<-get_upper_tri(correlacao)
  
melted_cor<-melt(uptr_correlacato, na.rm = TRUE) 
  
    melted_cor$value<-round(melted_cor$value,2)
    ggsave("../data/processed/figures/cor_cru_hyp_cau.png",

           
           
  melted_cor %>%
ggplot(., aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, limit = c(-1,1), space = "Lab", 
   name="Pearson\nCorrelation") +
  theme_minimal()+ 
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed() +
  theme(axis.title = element_blank()) +
    nice_layout +
  geom_text(aes(Var2, Var1, label = value), color = "black", size = 4) +
theme(
  legend.key.size = unit(4, 'cm'),
  legend.text = element_text(size=12),
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank(),
  legend.justification = c(1, 0),
  legend.position = c(0.3, 0.7),
  legend.direction = "horizontal")+
  guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5))

)
    
    
    
    
    


```


### plot fd and sweeps genome-wide

```{r}

    
       plot_fd_crops <-
    ggplot(df.tmp, aes(x=Position, y=f_dM)) +
    # Show all points
    geom_point(aes(alpha=0.1), color="#808080",  size=0.5) +
            nice_layout +
         geom_point(data=top_windows_crops_tree, 
             aes(x=Position,y=f_dM), 
             color='#b2df8a',fill="#b2df8a",
             size=2) +
  geom_line(data=df.tmp, aes(x=Position, y=quantile(crops_tree$f_dM, .995)), color="#b2df8a", fill="#b2df8a", linetype="dashed") +
    geom_point(data=bottom_windows_crops_tree, aes(x=Position, y=f_dM),color = "#808080", alpha=0.3)  +
  geom_point(data=bottom_windows_crops_tree, 
             aes(x=Position,y=f_dM), 
             color='#1f78b4', fill="#1f78b4",
             size=2) +
  geom_line(data=df.tmp, aes(x=Position, y=quantile(crops_tree$f_dM, .005)), color="#1f78b4", fill="#1f78b4",  linetype="dashed") +
      facet_grid(.~CHR, scales = "free", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank()) 
  
    
    plot_fd_crops

  
plot_sweep_caudatus<-     
    ggplot(sweeps_caudatus.df, aes(x=endpos, y=sweep_height)) +
     # ggplot(sweeps_caudatus.df) +       
     # geom_linerange(aes(xmin=tot, xmax=endpos, y=sweep_height)) +
 geom_point(shape="|", color="#000000",  size=4) +
            nice_layout +
      facet_grid(.~CHR, scales = "free_x", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(breaks=1, expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
    # xlab("Position (Mb")  +
      ylim(1,1) +
  ylab("sweep caudatus")



  
plot_sweep_cruentus<-     
    ggplot(sweeps_cruentus.df, aes(x=endpos, y=sweep_height)) +
     # ggplot(sweeps_cruentus.df) +
     # geom_linerange(aes(xmin=tot, xmax=endpos, y=sweep_height)) +
 geom_point(shape="|", color="#000000",  size=4) +
            nice_layout +
      facet_grid(.~CHR, scales = "free_x", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(breaks=1, expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
    # xlab("Position (Mb")  +
      ylim(1,1) +
    ylab("sweep cruentus")


  
plot_sweep_hypochondriacus<-     
    ggplot(sweeps_hypochondriacus.df, aes(x=endpos, y=sweep_height)) +
     # ggplot(sweeps_hypochondriacus.df) +
     # geom_linerange(aes(xmin=tot, xmax=endpos, y=sweep_height)) +
 geom_point(shape="|", color="#000000",  size=4) +
            nice_layout +
      facet_grid(.~CHR, scales = "free_x", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(breaks=1, expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
    # xlab("Position (Mb")  +
      ylim(1,1)  +
  ylab("sweep hypochondriacus")


ggsave("/Users/josedias/OneDrive/Stetter_Lab/GeneFlow/figures/plot_grid_sweep_fd_position.png",
    plot_grid(plot_fd_crops, plot_sweep_caudatus,plot_sweep_cruentus, plot_sweep_hypochondriacus, ncol = 1, align = "v"
),
height = 10, width =24)
  ####
    # theme(axis.text.x = element_blank() )


```



# only chr 16

```{r}
top_windows_crops_tree_sc16<-
  top_windows_crops_tree %>%
  filter(CHR=="16")

bottom_windows_crops_tree_sc16 <-
bottom_windows_crops_tree %>%
  filter(CHR=="16")


df.tmp_sc16<-
  df.tmp %>%
  filter(CHR=="16") 

sweeps_caudatus.df_sc16<-
sweeps_caudatus.df %>%
    filter(CHR=="16") 

sweeps_cruentus.df_sc16<-
sweeps_cruentus.df %>%
    filter(CHR=="16") 

sweeps_hypochondriacus.df_sc16<-
sweeps_hypochondriacus.df %>%
    filter(CHR=="16") 

       plot_fd_crops_sc16 <-
         df.tmp_sc16 %>%
    ggplot(., aes(x=Position, y=f_dM)) +
    # Show all points
    geom_point(aes(alpha=0.1), color="#808080",  size=0.5) +
            nice_layout +
         geom_point(data=top_windows_crops_tree_sc16, 
             aes(x=Position,y=f_dM), 
             color='#b2df8a',fill="#b2df8a",
             size=2) +
  geom_line(data=df.tmp_sc16, aes(x=Position, y=quantile(df.tmp_sc16$f_dM, .995)), color="#b2df8a", fill="#b2df8a", linetype="dashed") +
  geom_point(data=bottom_windows_crops_tree_sc16, 
             aes(x=Position,y=f_dM), 
             color='#1f78b4', fill="#1f78b4",
             size=2) +
  geom_line(data=df.tmp_sc16, aes(x=Position, y=quantile(df.tmp_sc16$f_dM, .005)), color="#1f78b4", fill="#1f78b4",  linetype="dashed") +
      # facet_grid(.~CHR, scales = "free", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank()) 
  

       
       
plot_sweep_caudatus_sc16<-     
    ggplot(sweeps_caudatus.df_sc16, aes(x=endpos, y=sweep_height)) +
     # ggplot(sweeps_hypochondriacus.df) +
     geom_linerange(aes(xmin=startpos, xmax=endpos, y=sweep_height), lwd=1.5) +
 # geom_point(color="#808080",  size=0.5) +
            nice_layout +
      # facet_grid(.~CHR, scales = "free_x", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(breaks=1, expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
    # xlab("Position (Mb")  +
      ylim(1,1) +
  ylab("sweep caudatus")



  
plot_sweep_cruentus_sc16<-     
    ggplot(sweeps_cruentus.df_sc16, aes(x=endpos, y=sweep_height)) +
     # ggplot(sweeps_hypochondriacus.df) +
     geom_linerange(aes(xmin=startpos, xmax=endpos, y=sweep_height), lwd=1.5) +
 # geom_point(color="#808080",  size=0.5) +
            nice_layout +
      # facet_grid(.~CHR, scales = "free_x", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(breaks=1, expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
    # xlab("Position (Mb")  +
      ylim(1,1) +
    ylab("sweep cruentus")


  
plot_sweep_hypochondriacus_sc16<-
    ggplot(sweeps_hypochondriacus.df_sc16, aes(x=endpos, y=sweep_height)) +
     # ggplot(sweeps_hypochondriacus.df) +
     geom_linerange(aes(xmin=startpos, xmax=endpos, y=sweep_height), lwd=1.5) +
 # geom_point(color="#808080",  size=0.5) +
            nice_layout +
      # facet_grid(.~CHR, scales = "free_x", space = "free_x") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(breaks=1, expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank(), axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
    # xlab("Position (Mb")  +
      ylim(1,1)  +
  ylab("sweep hypochondriacus")


ggsave("/Users/josedias/OneDrive/Stetter_Lab/GeneFlow/figures/plot_grid_sweep_fd_sc16.png",
    plot_grid(plot_fd_crops_sc16, plot_sweep_caudatus_sc16,plot_sweep_cruentus_sc16, plot_sweep_hypochondriacus_sc16, ncol = 1, align = "v"
),
height = 10, width =24)
  ####
    # theme(axis.text.x = element_blank() )

       
       
       

```



## test alternative fd plot

```{r}
install.packages("devtools")
devtools::install_github("PhanstielLab/bedtoolsr", force = T)
options(bedtools.path = "/Users/josedias/miniconda3/bin/")


top_windows_crops_tree <-
  df.tmp %>%
filter(f_dM > quantile(df.tmp$f_dM, .995)) %>%
  select(CHR, windowStart, windowEnd, f_dM, Position)
  

bottom_windows_crops_tree <-
    df.tmp %>%
 filter(f_dM <  quantile(df.tmp$f_dM, .005)) %>%
    select(CHR, windowStart, windowEnd, f_dM, Position)

sweeps_caudatus.df <-
sweeps_caudatus.df %>%
  rename(windowStart=startpos,windowEnd=endpos ) %>%
    select(CHR, windowStart, windowEnd)

 

interesection_crops_tree_sweep_tops<- bedtoolsr::bt.intersect(top_windows_crops_tree, sweeps_caudatus.df ) %>%
  rename(CHR=V1, windowStart=V2, windowEnd=V3, f_dM=V4)  %>%
          mutate(window_center=round(((windowStart+windowEnd)/2))) %>%
              mutate(Position = window_center/1e6) 
  

interesection_crops_tree_sweep_bottom<- bedtoolsr::bt.intersect(bottom_windows_crops_tree, sweeps_caudatus.df) %>%
  rename(CHR=V1, windowStart=V2, windowEnd=V3, f_dM=V4) %>%
          mutate(window_center=round(((windowStart+windowEnd)/2))) %>%
              mutate(Position = window_center/1e6) 

interesection_crops_tree_sweeps_all<-rbind(interesection_crops_tree_sweep_bottom, interesection_crops_tree_sweep_tops)
  
  
# top_windows_crops_tree <-  crops_tree %>%
#     filter(str_detect(chr, "Scaffold")) %>%
#                  filter(f_dM>quantile(crops_tree$f_dM, .995)) %>%
#             mutate(Position = window_center/1e6)
# 
# 
# bottom_windows_crops_tree <-  crops_tree %>%
#     filter(str_detect(chr, "Scaffold")) %>%
#                  filter(f_dM<quantile(crops_tree$f_dM, .005)) %>%
#             mutate(Position = window_center/1e6)
# 



       plot_fd_crops <-
    ggplot(df.tmp, aes(x=Position, y=f_dM)) +
    # Show all points
    geom_point(alpha=0.1, color="#dcdcdc",  size=0.5) +
            nice_layout +
         geom_point(data=top_windows_crops_tree, 
             aes(x=Position,y=f_dM), 
             color='#b2df8a',fill="#b2df8a",
             size=2) +
  geom_line(data=df.tmp, aes(x=Position, y=quantile(df.tmp$f_dM, .995)), color="#b2df8a", fill="#b2df8a", linetype="dashed") +
    geom_point(data=bottom_windows_crops_tree, aes(x=Position, y=f_dM),color = "#808080", alpha=0.3)  +
  geom_point(data=bottom_windows_crops_tree, 
             aes(x=Position,y=f_dM), 
             color='#1f78b4', fill="#1f78b4",
             size=2) +
               facet_grid(.~CHR, scales = "free", space = "free_x") +
  geom_line(data=df.tmp, aes(x=Position, y=quantile(df.tmp$f_dM, .005)), color="#1f78b4", fill="#1f78b4",  linetype="dashed")  +
         geom_point(data=interesection_crops_tree_sweeps_all, aes(x=Position, y=f_dM),
             size=2.5,  color="red") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits) +
      theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank()) +
         clear_layout +
           theme(guides(fill = guide_colorbar(barwidth = 7, barheight = 1,
                title.position = "top", title.hjust = 0.5)))
  plot_fd_crops

  reds.w <- c("#FFAD7E", "#E9874F", "#D96726", "#AE4A12", "#873100") # method 1

  
      ggplot(df.tmp, aes(x=Position, y=f_dM)) +
    # Show all points
    geom_point(aes(color=as.factor(chr)), alpha=0.5,  size=0.5)+
            # nice_layout +
         geom_point(data=top_windows_crops_tree, 
             aes(x=Position,y=f_dM), 
             color='#b2df8a',fill="#b2df8a",
             size=2) +
  geom_line(data=df.tmp, aes(x=Position, y=quantile(df.tmp$f_dM, .995)), color="#b2df8a", fill="#b2df8a", linetype="dashed") +
    geom_point(data=bottom_windows_crops_tree, aes(x=Position, y=f_dM),color = "#808080", alpha=0.3)  +
  geom_point(data=bottom_windows_crops_tree, 
             aes(x=Position,y=f_dM), 
             color='#1f78b4', fill="#1f78b4",
             size=2) +
               facet_grid(.~CHR, scales = "free", space = "free_x") +
  geom_line(data=df.tmp, aes(x=Position, y=quantile(df.tmp$f_dM, .005)), color="#1f78b4", fill="#1f78b4",  linetype="dashed")  +
         geom_point(data=interesection_crops_tree_sweeps_all, aes(x=Position, y=f_dM),
             size=2.5,  color="red") +
              # scale_x_continuous( label = axisdf$CHR, breaks= axisdf$center ) +
    scale_y_continuous(expand = c(0, 0.1)) +  # expand=c(0,0)removes space between plot area and x axis  +
  scale_x_continuous(labels = addUnits, expand = c(0,0)) +
         clear_layout +
        theme(
    panel.spacing = unit(0,'lines')
  ) +
              theme(axis.text.x = element_text(angle=90, hjust = 1, vjust=1, size=10), legend.position = "none", axis.title.x = element_blank()) +
        theme(legend.position = "none") +
            scale_color_manual(values = rep(c("#dcdcdc", "#c0c0c0"), 16 ))
            # scale_color_manual(values = rep(my_cols, 16 )) 
     # ggplot() +       
     # geom_linerange(aes(xmin=tot, xmax=endpos, y=sweep_height)) +
 geom_point(sweeps_caudatus.df, aes(x=endpos, y=sweep_height), shape="|", color="#000000",  size=4) 

      
      

```


# PIR summary
```{r}

windows_full<- crops_tree %>%
  filter(str_detect(chr, "Scaffold")) %>%
 filter(f_dM<quantile(crops_tree$f_dM, .005) | f_dM>quantile(crops_tree$f_dM, .995)) %>%
  group_by(chr) %>%
  summarise(covered_bp=sum(difference)) %>%
    separate(chr, into = c("id", "no"), remove = F, convert = T) %>%
    arrange(id, no) %>%
    select(-id, -no)





ggsave("../data/processed/figures/fd_distribution_hyb_SA_hyp_cru.png",
 crops_tree %>%
     filter(str_detect(chr, "Scaffold")) %>%
 filter(f_dM<quantile(crops_tree$f_dM, .005) | f_dM>quantile(crops_tree$f_dM, .995)) %>%
  mutate(difference=windowEnd-windowStart) %>%
             mutate(Position = windowStart/1e6) %>%
  ggplot(aes(y=difference, x=Position)) +
   geom_line() +
  facet_wrap(.~chr, scales ="free") +
   theme_bw() +
   nice_layout +
         theme(axis.text.x = element_text(angle = 45 ,size =22)) 
   , width=28,height =28)

  
  
windows_full

chr_sizes<- fread("../data/processed/chr_sizes_list_Scaffolds.txt") %>%
  rename(chr=V1, chr_size=V2)

summary_windows<- windows_full %>%
  inner_join(chr_sizes) %>%
  mutate(introgressed_genome=as.numeric(covered_bp)/as.numeric(chr_size))


ggsave("../data/processed/figures/fd_coverage_by_chr_hyb_SA_hyp_cru.png",
ggplot(summary_windows, aes(x=chr, y=covered_bp), alpha(0.3)) +
        geom_bar(stat="identity", aes(fill=introgressed_genome)) +
    geom_col(aes(x=chr, y=chr_size),  alpha=0.3, stat="identity") +
    theme_bw() +
      theme(axis.text.x = element_text(angle = 45 ,size =22)) +
        theme(axis.text.y = element_text(size =24)) +
  theme(axis.title = element_text(size=22)) +
     theme(legend.position = "none")  +
      geom_text(aes(label=sprintf(introgressed_genome, fmt = '%#.3f', size=24), vjust=0)) 
, width=18,height =12)
  nice_layout



fwrite(summary_windows, "../data/processed/geneflow_summary/coveredbp_geneflow_hyb_SA_hyp_cru.txt", quote=F, sep="\t")
fwrite(crops_tree, "../data/processed/geneflow_summary/dsuite_stats_geneflow_hyb_SA_hyp_cru.txt", quote=F, sep="\t")

ggsave("../data/processed/figures/fdm_ddistribution_normal_hyb_SA_hyp_cru.png",
crops_tree %>%
   filter(str_detect(chr, "Scaffold")) %>%
  ggplot(aes(x=f_dM)) +
  geom_histogram(aes(y = ..density..)) +
  stat_function(fun = dnorm,
                args = list(mean = mean(crops_tree$f_dM),
                            sd = sd(crops_tree$f_dM)),
                col = "red",
                size = 1, linetype="dashed") +
          theme(axis.text.x = element_text(angle = 45 ,size =22)) +
  facet_wrap(.~chr) +
  theme_bw() +
  nice_layout , 
width=28,height =28)
  
options(scipen=999)


```



```{r}

top_windows_crops_tree <-  crops_tree %>%
    filter(str_detect(chr, "Scaffold")) %>%
                 filter(f_dM>quantile(crops_tree$f_dM, .995)) %>%
            mutate(Position = window_center/1e6)


bottom_windows_crops_tree <-  crops_tree %>%
    filter(str_detect(chr, "Scaffold")) %>%
                 filter(f_dM<quantile(crops_tree$f_dM, .005)) %>%
            mutate(Position = window_center/1e6)


# ggsave("../data/processed/figures/fd_summary_hyb_SA_hyp_cru_all_chr.png",
ggplot() +
geom_point(data=crops_tree, aes(x=Position, y=f_dM),color = "#808080", alpha=0.1)  +
  geom_point(data=top_windows_crops_tree, 
             aes(x=Position,y=f_dM), 
             color='#b2df8a',
             size=3) +
  geom_line(data=crops_tree, aes(x=Position, y=quantile(crops_tree$f_dM, .995)), color="#b2df8a",  linetype="dashed") +
    geom_point(data=bottom_windows_crops_tree, aes(x=Position, y=f_dM),color = "#808080", alpha=0.3)  +
  geom_point(data=bottom_windows_crops_tree, 
             aes(x=Position,y=f_dM), 
             color='#1f78b4',
             size=3) +
  geom_line(data=crops_tree, aes(x=Position, y=quantile(crops_tree$f_dM, .005)), color="#1f78b4",  linetype="dashed") +
  facet_wrap(.~chr, scales="free") +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 45 ,size =22)) +
        theme(axis.text.y = element_text(size =24)) +
  theme(axis.title = element_text(size=22)) +
  nice_layout +
     theme(legend.position = "none")
# ,
# width=28,height =28)



```


zoom in QTL 16

```{r}

plot_fdm<-  
  ggplot() +
geom_point(data=crops_tree, aes(x=Position, y=f_dM),color = "#808080", alpha=0.1)  +
  geom_point(data=top_window_crop_tree, 
             aes(x=Position,y=f_dM), 
             color='#b2df8a',
             size=3) +
  geom_line(data=crops_tree, aes(x=Position, y=quantile(crops_tree$f_dM, .99)), color="#b2df8a",  linetype="dashed") +
    # geom_line(data=crops_tree, aes(x=Position, y=quantile(crops_tree$f_dM, .01)), color="#b2df8a",  linetype="dashed") +
    geom_point(data=crops_tree_switched, aes(x=Position, y=f_dM),color = "#808080", alpha=0.3)  +
  geom_point(data=top_window_crop_tree_switched, 
             aes(x=Position,y=f_dM), 
             color='#1f78b4',
             size=3) +
  geom_line(data=crops_tree_switched, aes(x=Position, y=quantile(crops_tree_switched$f_dM, .99)), color="#1f78b4",  linetype="dashed") +
    # geom_line(data=crops_tree_switched, aes(x=Position, y=quantile(crops_tree_switched$f_dM, .01)), color="#1f78b4",  linetype="dashed") +
    theme_bw() +
     theme( text = element_text(size = 30)) +
    labs(title = "fdM caudatus gene flow into crops") +
    xlab("Position on chromossome 16 (Mb)") +
   guides(fill=guide_legend(title="crop")) +
        geom_vline(xintercept=0.976,linetype='dashed', color='red', size=0.5) +
    geom_vline(xintercept=0.989, linetype='dashed', color='red', size=0.5) 

plot_fdm

ggsave("/Users/josedias/mount/projects/ag-stetter/jdias/projects/geneflow/data/processed/figures/fdm_hyp_cru_cau__cru_hyp_cau_sc16_vline.png", plot_fdm, width = 12, height =6)
```



```{r}

crops_tree_QTL_16 <- crops_tree %>%
  filter(windowEnd<1050000) %>%
  filter(windowStart > 900000)


crops_tree_switched_QTL_16 <- crops_tree_switched %>%
  filter(windowEnd<1050000) %>%
  filter(windowStart > 900000)




top_window_crop_tree<- crops_tree %>% 
               filter(f_dM>quantile(crops_tree$f_dM, .005)) %>%

             # filter(f_dM>quantile(crops_tree$f_dM, .99) | f_dM<quantile(crops_tree$f_dM, .01)) %>%
          mutate(Position = windowEnd/1e6) 


bottom_window_crop_tree<- crops_tree %>% 
               filter(f_dM<quantile(crops_tree$f_dM, .005)) %>%

             # filter(f_dM>quantile(crops_tree$f_dM, .99) | f_dM<quantile(crops_tree$f_dM, .01)) %>%
          mutate(Position = windowEnd/1e6) 
    

filter(windowEnd<1050000) %>%
  filter(windowStart > 900000)




top_window_crop_tree_switched<- crops_tree_switched %>% 
               filter(f_dM>quantile(crops_tree_switched$f_dM, .99)) %>%
             # filter(f_dM>quantile(crops_tree_switched$f_dM, .99) | f_dM<quantile(crops_tree_switched$f_dM, .01)) %>%
          mutate(Position = windowEnd/1e6) %>%
    filter(windowEnd<1050000) %>%
  filter(windowStart > 900000)





plot_fdm_QTL16<-  
  ggplot() +
geom_point(data=crops_tree_QTL_16, aes(x=windowStart, y=f_dM),color = "#808080", alpha=0.1)  +
  geom_point(data=top_window_crop_tree, 
             aes(x=windowStart,y=f_dM), 
             color='#b2df8a',
             size=3) +
  geom_line(data=crops_tree_QTL_16, aes(x=windowStart, y=quantile(crops_tree$f_dM, .99)), color="#b2df8a",  linetype="dashed") +
    # geom_line(data=crops_tree, aes(x=Position, y=quantile(crops_tree$f_dM, .01)), color="#b2df8a",  linetype="dashed") +
    geom_point(data=crops_tree_switched_QTL_16, aes(x=windowStart, y=f_dM),color = "#808080", alpha=0.3)  +
  geom_point(data=top_window_crop_tree_switched, 
             aes(x=Position,y=f_dM), 
             color='#1f78b4',
             size=3) +
  geom_line(data=crops_tree_switched_QTL_16, aes(x=windowStart, y=quantile(crops_tree_switched$f_dM, .99)), color="#1f78b4",  linetype="dashed") +
    # geom_line(data=crops_tree_switched, aes(x=Position, y=quantile(crops_tree_switched$f_dM, .01)), color="#1f78b4",  linetype="dashed") +
    theme_bw() +
     theme( text = element_text(size = 30)) +
    labs(title = "fdM caudatus gene flow into crops") +
    xlab("Position on chromossome 16 (bp)") +
   guides(fill=guide_legend(title="crop")) +
        geom_vline(xintercept=976000,linetype='dashed', color='red', size=0.5) +
    geom_vline(xintercept=989000, linetype='dashed', color='red', size=0.5) 

plot_fdm_QTL16

options(scipen = 999)

ggsave("/Users/josedias/mount/projects/ag-stetter/jdias/projects/geneflow/data/processed/figures/fdm_hyp_cru_cau__cru_hyp_cau_QT:16_highlighted.png", plot_fdm, width = 12, height =6)

  
```



```{r}

crops_tree_cru_hyp_cau<- fread("/Users/josedias/mount/projects/ag-stetter/jdias/projects/geneflow/data/processed/Dsuite_out/cruentus_hypochondriacus_caudatus_localFstats_Dsuite_Dinvestigate_w100_fullgenome_crops_trios_100_1.txt") 

```


```{r}

crops_tree_cru_hyp_cau_sc3<- crops_tree_cru_hyp_cau %>%
      filter(chr=="Scaffold_3") %>%
          mutate(Position = windowEnd/1e6)


top_window_crops_tree_cru_hyp_cau_sc3<- crops_tree_cru_hyp_cau_sc3 %>% 
             filter(f_dM>quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .99))  %>%
          mutate(Position = windowEnd/1e6)



bottomn_window_crops_tree_cru_hyp_cau_sc3<- crops_tree_cru_hyp_cau_sc3 %>% 
             filter(f_dM<quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .01)) %>%
          mutate(Position = windowEnd/1e6)


  

plot_fdm_crops_tree_cru_hyp_cau_sc3 <-  
  ggplot() +
geom_point(data=crops_tree_cru_hyp_cau_sc3, aes(x=windowEnd, y=f_dM),color = "#808080", alpha=0.1)  +
  geom_point(data=top_window_crops_tree_cru_hyp_cau_sc3, 
             aes(x=windowEnd,y=f_dM), 
             color='#1f78b4',
             size=3) +
    geom_point(data=bottomn_window_crops_tree_cru_hyp_cau_sc3, 
             aes(x=windowEnd,y=f_dM), 
             color='#b2df8a',
             size=3) +
  geom_line(data=crops_tree_cru_hyp_cau_sc3, aes(x=windowEnd, y=quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .99)), color="#1f78b4",  linetype="dashed") +
    geom_line(data=crops_tree_cru_hyp_cau_sc3, aes(x=windowEnd, y=quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .01)), color="#b2df8a",  linetype="dashed") +
       theme( text = element_text(size = 30)) +
    labs(title = "fdM ((cruentus,hybridus),(caudatus))") +
    xlab("Position on chromossome 3 (Mb)") +
  geom_vline(xintercept=5881516,linetype='dashed', color='red', size=0.5) +
    geom_vline(xintercept=5966304, linetype='dashed', color='red', size=0.5) +
      theme_bw()



plot_fdm_crops_tree_cru_hyp_cau_sc3

ggsave("/Users/josedias/mount/projects/ag-stetter/jdias/projects/geneflow/data/processed/figures/fdm_cru_hyp_cau_sc3.png", plot_fdm_crops_tree_cru_hyp_cau_sc3, width = 12, height =6)


```


##QTL 3 5,881,516−5,966,304

```{r}
crops_tree_cru_hyp_cau_QTL3<- crops_tree_cru_hyp_cau_sc3 %>%
filter(windowEnd<6000000) %>%
  filter(windowEnd>5850000) %>%
  mutate(Position = windowEnd/1e6)


top_window_crops_tree_cru_hyp_cau_QTL3<- crops_tree_cru_hyp_cau_sc3 %>% 
             filter(f_dM>quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .99))%>%
  filter(windowEnd<6000000) %>%
  filter(windowEnd>5850000) %>%
          mutate(Position = windowEnd/1e6)

bottomn_window_crops_tree_cru_hyp_cau_QTL3<- crops_tree_cru_hyp_cau_sc3 %>% 
             filter(f_dM<quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .01)) %>%
    filter(windowEnd<6000000) %>%
  filter(windowEnd>5850000) %>%
          mutate(Position = windowEnd/1e6)




  

plot_fdm_crops_tree_cru_hyp_cau_QTL3 <-  
  ggplot() +
geom_point(data=crops_tree_cru_hyp_cau_QTL3, aes(x=windowEnd, y=f_dM),color = "#808080", alpha=0.1)  +
  geom_point(data=top_window_crops_tree_cru_hyp_cau_QTL3, 
             aes(x=windowEnd,y=f_dM), 
             color='#1f78b4',
             size=3) +
      geom_point(data=bottomn_window_crops_tree_cru_hyp_cau_QTL3, 
             aes(x=windowEnd,y=f_dM), 
             color='#b2df8a',
             size=3) +
  geom_line(data=top_window_crops_tree_cru_hyp_cau_QTL3, aes(x=windowEnd, y=quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .99)), color="#b2df8a",  linetype="dashed") +
    geom_line(data=top_window_crops_tree_cru_hyp_cau_QTL3, aes(x=windowEnd, y=quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .01)), color="#b2df8a",  linetype="dashed") +
       theme( text = element_text(size = 30)) +
    labs(title = "fdM ((cruentus,hybridus),(caudatus)), QTL 3") +
    xlab("Position on chromossome 3 (Mb)") +
  geom_vline(xintercept=5881516,linetype='dashed', color='red', size=0.5) +
    geom_vline(xintercept=5966304, linetype='dashed', color='red', size=0.5) +
      theme_bw()




plot_fdm_crops_tree_cru_hyp_cau_QTL3


ggsave("/Users/josedias/mount/projects/ag-stetter/jdias/projects/geneflow/data/processed/figures/fdm_cru_hyp_cau_QTL3.png", plot_fdm_crops_tree_cru_hyp_cau_QTL3, width = 12, height =6)


```



## QTL 9


```{r}

crops_tree_cru_hyp_cau_sc9<- crops_tree_cru_hyp_cau %>%
      filter(chr=="Scaffold_9") %>%
          mutate(Position = windowEnd/1e6)


top_window_crops_tree_cru_hyp_cau_sc9<- crops_tree_cru_hyp_cau_sc9 %>% 
             filter(f_dM>quantile(crops_tree_cru_hyp_cau_sc9$f_dM, .99))  %>%
          mutate(Position = windowEnd/1e6)



bottomn_window_crops_tree_cru_hyp_cau_sc9<- crops_tree_cru_hyp_cau_sc9 %>% 
             filter(f_dM<quantile(crops_tree_cru_hyp_cau_sc9$f_dM, .01)) %>%
          mutate(Position = windowEnd/1e6)


  

plot_fdm_crops_tree_cru_hyp_cau_sc9 <-  
  ggplot() +
geom_point(data=crops_tree_cru_hyp_cau_sc9, aes(x=windowEnd, y=f_dM),color = "#808080", alpha=0.1)  +
  geom_point(data=top_window_crops_tree_cru_hyp_cau_sc9, 
             aes(x=windowEnd,y=f_dM), 
             color='#1f78b4',
             size=3) +
    geom_point(data=bottomn_window_crops_tree_cru_hyp_cau_sc9, 
             aes(x=windowEnd,y=f_dM), 
             color='#b2df8a',
             size=3) +
  geom_line(data=crops_tree_cru_hyp_cau_sc9, aes(x=windowEnd, y=quantile(crops_tree_cru_hyp_cau_sc9$f_dM, .99)), color="#1f78b4",  linetype="dashed") +
    geom_line(data=crops_tree_cru_hyp_cau_sc9, aes(x=windowEnd, y=quantile(crops_tree_cru_hyp_cau_sc9$f_dM, .01)), color="#b2df8a",  linetype="dashed") +
       theme( text = element_text(size = 30)) +
    labs(title = "fdM ((cruentus,hybridus),(caudatus))") +
    xlab("Position on chromossome 9 (Mb)") +
  geom_vline(xintercept= 14260388,linetype='dashed', color='red', size=0.5) +
    geom_vline(xintercept=14855666, linetype='dashed', color='red', size=0.5) +  
      theme_bw()



plot_fdm_crops_tree_cru_hyp_cau_sc9

ggsave("/Users/josedias/mount/projects/ag-stetter/jdias/projects/geneflow/data/processed/figures/fdm_cru_hyp_cau_sc9.png", plot_fdm_crops_tree_cru_hyp_cau_sc9, width = 12, height =6)


```


##QTL 3 5,881,516−5,966,304

```{r}
crops_tree_cru_hyp_cau_QTL9<- crops_tree_cru_hyp_cau_sc9 %>%
  filter(windowEnd<14900000) %>%
  filter(windowEnd>14200000) %>%
  mutate(Position = windowEnd/1e6)


top_window_crops_tree_cru_hyp_cau_QTL9<- crops_tree_cru_hyp_cau_sc3 %>% 
             filter(f_dM>quantile(crops_tree_cru_hyp_cau_sc9$f_dM, .99))%>%
  filter(windowEnd<14900000) %>%
  filter(windowEnd>14200000) %>%
          mutate(Position = windowEnd/1e6)

bottomn_window_crops_tree_cru_hyp_cau_QTL9<- crops_tree_cru_hyp_cau_sc9 %>% 
             filter(f_dM<quantile(crops_tree_cru_hyp_cau_sc9$f_dM, .01)) %>%
  filter(windowEnd<14900000) %>%
  filter(windowEnd>14200000) %>%
          mutate(Position = windowEnd/1e6)




  

plot_fdm_crops_tree_cru_hyp_cau_QTL9 <-  
  ggplot() +
geom_point(data=crops_tree_cru_hyp_cau_QTL9, aes(x=windowEnd, y=f_dM),color = "#808080", alpha=0.1)  +
  geom_point(data=top_window_crops_tree_cru_hyp_cau_QTL9, 
             aes(x=windowEnd,y=f_dM), 
             color='#1f78b4',
             size=3) +
      geom_point(data=bottomn_window_crops_tree_cru_hyp_cau_QTL9, 
             aes(x=windowEnd,y=f_dM), 
             color='#b2df8a',
             size=3) +
  geom_line(data=top_window_crops_tree_cru_hyp_cau_QTL3, aes(x=windowEnd, y=quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .99)), color="#b2df8a",  linetype="dashed") +
    geom_line(data=top_window_crops_tree_cru_hyp_cau_QTL3, aes(x=windowEnd, y=quantile(crops_tree_cru_hyp_cau_sc3$f_dM, .01)), color="#b2df8a",  linetype="dashed") +
       theme( text = element_text(size = 30)) +
    labs(title = "fdM ((cruentus,hybridus),(caudatus)), QTL 9") +
    xlab("Position on chromossome 9 (Mb)") +
  geom_vline(xintercept= 14260388,linetype='dashed', color='red', size=0.5) +
    geom_vline(xintercept=14855666, linetype='dashed', color='red', size=0.5) +  
      theme_bw()




plot_fdm_crops_tree_cru_hyp_cau_QTL9


ggsave("/Users/josedias/mount/projects/ag-stetter/jdias/projects/geneflow/data/processed/figures/fdm_cru_hyp_cau_QTL9.png", plot_fdm_crops_tree_cru_hyp_cau_QTL9, width = 12, height =6)


```


# code from before
```{r}

top_window_hyb_hyp_cau<- hyb_hyp_cau_tree_w1000 %>% 
             filter(f_dM>=quantile(hyb_hyp_cau_tree_w1000$f_dM, .95))
               
hyb_hyp_cau_tree_w1000<- hyb_hyp_cau_tree_w1000  %>%
    mutate(Position = windowEnd/1e6)
  # filter(f_dM > 0.134597795) %>%


plot_fdm<-  ggplot() +
geom_point(data=hyb_hyp_cau_tree_w1000, aes(x=Position, y=f_dM),color = "#b2df8a", alpha=0.3)  +
  geom_point(data=top_window_hyb_hyp_cau, 
             aes(x=Position,y=f_dM), 
             color='#b2df8a',
             size=3) +
  geom_line(data=hyb_hyp_cau_tree_w1000, aes(x=Position, y=quantile(hyb_hyp_cau_tree_w1000$f_dM, .95)), color="#b2df8a",  linetype="dashed") +
    geom_point(data=hyb_cru_cau_tree_w1000, aes(x=Position, y=f_dM),color = "#1f78b4", alpha=0.3)  +
  geom_point(data=top_windows_hyb_cru_cau, 
             aes(x=Position,y=f_dM),9
             color='#1f78b4',
             size=3) +
  geom_line(data=hyb_cru_cau_tree_w1000, aes(x=Position, y=quantile(hyb_cru_cau_tree_w1000$f_dM, .95)), color="#1f78b4",  linetype="dashed") +
    theme_bw() +
     theme( text = element_text(size = 30)) +
    labs(title = "fdM caudatus gene flow into crops") +
    xlab("Position on chromossome 16 (Mb)") +
   guides(fill=guide_legend(title="crop"))


  ggsave("/Users/josedias/mount/projects/ag-stetter/jdias/projects/geneflow/data/processed/figures/fdm_cruenuts_hypochondriacus_caudatus.png", plot_fdm, width = 14, height = 7)

    

top_windows_hyb_cru_cau<- hyb_cru_cau_tree_w1000 %>% 
             filter(f_dM>=quantile(hyb_cru_cau_tree_w1000$f_dM, .95))
               
hyb_cru_cau_tree_w1000 <- hyb_cru_cau_tree_w1000 %>%
    mutate(Position = windowEnd/1e6)

  # filter(f_dM > 0.134597795) %>%
  ggplot() +
geom_point(data=hyb_cru_cau_tree_w1000, aes(x=windowEnd, y=f_dM),color = "1f78b4", alpha=0.3)  +
  geom_point(data=top_windows, 
             aes(x=windowEnd,y=f_dM), 
             color='red',
             size=3) +
  geom_line(data=hyb_cru_cau_tree_w1000, aes(x=windowEnd, y=quantile(hyb_cru_cau_tree_w1000$f_dM, .95)), color="1f78b4",  linetype="dashed") +
  # scale_colour_manual(labels = c("<3000", ">3000"), values=c('blue', 'red')) + 
  theme_cowplot() +
    labs(title = "fdM cruentus-caudatus")
    geom_text(show.legend = F, title="cruentus-caudatus")


    

hyb_cru_cau_tree_w1000 %>%
  arrange(f_dM, desc=T) %>%
  filter(windowStart<5000000)


  
  
```

```{r}



hyb_hyp_cau_tree_w1000 %>%
    filter(f_dM > quantile(f_dM, .08))

  group_by(window_center) %>% 
 select(f_dM, window_center) %>% 
 arrange(desc(f_dM)) %>%
  filter(f_dM > quantile(f_dM, .08))

crops_tree_switched<- crops_tree_switched %>%
  mutate(window_center=(windowStart+windowEnd/2))


  ggplot(NULL) +
  geom_point(data=crops_tree_w1000, aes(x=window_center, y=f_dMM, color="blue")) +
  geom_point(data=crops_tree_switched_w1000, aes(x=window_center, y=f_dMM, color="red")) +
scale_color_manual(
    values = c("red", "blue"),
    labels = c("hyp_cru_cau", "cru_hyp_cau" )) +
  theme_cowplot()
  
  
  
   crops_tree_w1000 %>%
        # filter(f_dM<1 & f_dM >-1) %>%
  ggplot()   +  
    geom_point(aes(x=window_center, y=f_d), col="blue") +
    geom_line(data = crops_tree_switched_w1000, aes(x=window_center, y=mean(f_d)), col="blue", linetype="dashed") +
    geom_point( aes(x=window_center, y=D), col="red") +
        geom_line(data = crops_tree_switched_w1000, aes(x=window_center, y=mean(D)), col="red", linetype="dashed") +
      geom_point( aes(x=window_center, y=f_dM), col="green") +
            geom_line(data = crops_tree_switched_w1000, aes(x=window_center, y=mean(D)), col="green", linetype="dashed") +
nice_layout   
   
```


