##############################################
# Example config for msa_pipeline Snakefile  #
##############################################

########################
# REQUIRED PARAMETERS  #
########################

# Reference species name
# The name should match the name of a fasta file in "msa_pipeline/data" but NOT contain the .fa suffix
refName: Ahypochondriacus_new

# Query species to be aligned to reference
# The species names should each match a fasta file in "msa_pipeline/data" but NOT contain the .fa suffix
species:

  - Bdistachyon
  - Bvulgaris
  - Cquinoa
  - Gmax
  - Hannuus
  - Mguttatus
  - Mtruncatula
  - Osativa
  - Ptrichocarpa
  - Pvulgaris
  - Sbicolor
  - Slycopersicum
  - Sviridis
  - Vvinifera
  - MonoeViroflay
  
######################################
# OPTIONAL PARAMETERS  FOR ALIGNMENT #
######################################

# Split input fasta files into N chunks for improved parallel processing
# Chunks are aligned in parallel if sufficient threads are available
# Setting N to be greater than the minimum chromosome/scaffold number may lead to errors
splitFastaN: 1

# Set alignment tool: last|minimap2|gsalign
aligner: last

# Change default alignment parameters
lastParams: "-m 10 -j 3 -u 1 -p HOXD70"
minimap2Params: "-a -cx asm20"
gsalignParams: "-sen -no_vcf"

# Without last-split, the alignments are many-many after lastal, and many-one afer
# chaining and netting.  
lastSplit:
# For one-to-one last alignments, comment the above and uncomment the lastSplit line below
#lastSplit: " | last-split | maf-swap | last-split | maf-swap "

# Roast multiple alignment parameters
roastParams: "+ X=2 E="

# Newick format species tree for roast
# It must contain the reference and all other species in the alignment
# If left empty, tree will be calculated from genome sequences with mashtree 
speciesTree: "((((((Pvulgaris,Gmax),Mtruncatula),Ptrichocarpa),Vvinifera),((((Cquinoa,MonoeViroflay),Bvulgaris),Ahypochondriacus_new),((Mguttatus,Slycopersicum),Hannuus))),((Bdistachyon,Osativa),(Sviridis,Sbicolor)));"

#################################################
# OPTIONAL PARAMETERS FOR CONSERVATION ANALYSIS #
#################################################

# When callling conservation set the max number of sites to use to calculate the neutral model
# Higher numbers may slow down the analysis without providing a better model
maxNeutralSites: 10000000

# A GFF file with CDS features must be provided in the /data dir to use a neutral model based on 4-fold degenerate sites
refGFF: Ahypochondriacus_new.gff3
