#!/bin/bash -l
#SBATCH --partition=devel-rh7
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=46gb
#SBATCH --account=UniKoeln
#SBATCH --mail-user=jgoncal1@uni-koeln.de
#SBATCH --error /scratch/jgoncal1/logs/errors/bacftools_annotate_%j
#SBATCH -o /scratch/jgoncal1/logs/bacftools_annotate_%j
#SBATCH -D /projects/ag-stetter/jdias/projects/geneflow/code/

source /home/jgoncal1/.bashrc
module load miniconda/py38_4.9.2
conda activate base_jgd

vcf_file="../data/processed/phased_subsampled_minmaf0005.vcf.gz" # preifx of files generated by csplit

bcftools annotate --set-id +'%CHROM\_%POS' $vcf_file > ../data/processed/annotated_$(basename $vcf_file).recode.vcf.gz 

