#!/bin/bash -l
#SBATCH --partition=devel
#SBATCH --time=1:00:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=46gb
#SBATCH --account=UniKoeln
#SBATCH --mail-user=jgoncal1@uni-koeln.de
#SBATCH --error /scratch/jgoncal1/logs/errors/bacftools_reeahder_%j
#SBATCH -o /scratch/jgoncal1/logs/bacftools_rehaeder%j
#SBATCH -D /projects/ag-stetter/jdias/projects/geneflow/code/


source /home/jgoncal1/.bashrc
module load miniconda/py38_4.9.2
conda activate base_jgd 

vcf_file_prefix="/projects/ag-stetter/jdias/projects/GeneFlow/data/processed/VCF_files/dovcf_pop_mind73_onlyproperpairs_trim_setMinDepth73_setMaxDepthInd150_geneflowsamples_Scaffold_" # preifx of files generated by csplit
samplesnames="file_lists/samples_geneflow.txt"
for scaffold in {1..15};do # loop per scaffold

echo $vcf_file_prefix$scaffold.vcf.gz 
echo ../data/processed/$(basename $vcf_file_prefix)$scaffold.recode.vcf.gz 

bcftools reheader -s $samplesnames $vcf_file_prefix$scaffold.vcf.gz > ../data/processed/reheadered_Scaffold_$scaffold.bcf 

tabix -p bcf ../data/processed/reheadered_Scaffold_$scaffold.bcf

done
